version: '3'
services:
  servicio1:
    image: par_server
    ports:
      - 4000:4000

  servicio2:
    container_name: par-mariadb
    image: mariadb:10.6.14
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: api_database
      MYSQL_USER: root
  
  servicio3:
    container_name: par-mongodb
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mypassword